import tkinter as tk
from tkinter import ttk
import re

# -----------------------------
# Password Checking Function
# -----------------------------
def check_password():

    password = password_entry.get()

        score = 0

            # Length Check
                if len(password) >= 8:
                        score += 1

                            # Uppercase Check
                                if re.search(r"[A-Z]", password):
                                        score += 1

                                            # Lowercase Check
                                                if re.search(r"[a-z]", password):
                                                        score += 1

                                                            # Number Check
                                                                if re.search(r"\d", password):
                                                                        score += 1

                                                                            # Special Character Check
                                                                                if re.search(r"[!@#$%^&*()_+=<>?/]", password):
                                                                                        score += 1

                                                                                            # -----------------------------
                                                                                                # Password Result + Progress Bar
                                                                                                    # -----------------------------

                                                                                                        # Weak Password
                                                                                                            if score <= 2:

                                                                                                                    result_label.config(
                                                                                                                                text="[ WEAK PASSWORD ]",
                                                                                                                                            fg="red"
                                                                                                                                                    )

                                                                                                                                                            progress["value"] = 30

                                                                                                                                                                # Medium Password
                                                                                                                                                                    elif score <= 4:

                                                                                                                                                                            result_label.config(
                                                                                                                                                                                        text="[ MEDIUM PASSWORD ]",
                                                                                                                                                                                                    fg="orange"
                                                                                                                                                                                                            )

                                                                                                                                                                                                                    progress["value"] = 70

                                                                                                                                                                                                                        # Strong Password
                                                                                                                                                                                                                            else:

                                                                                                                                                                                                                                    result_label.config(
                                                                                                                                                                                                                                                text="[ STRONG PASSWORD ]",
                                                                                                                                                                                                                                                            fg="#00ff00"
                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                            progress["value"] = 100

                                                                                                                                                                                                                                                                            # -----------------------------
                                                                                                                                                                                                                                                                            # Show / Hide Password
                                                                                                                                                                                                                                                                            # -----------------------------
                                                                                                                                                                                                                                                                            def toggle_password():

                                                                                                                                                                                                                                                                                if password_entry.cget('show') == '*':
                                                                                                                                                                                                                                                                                        password_entry.config(show='')

                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                    password_entry.config(show='*')

                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                    # Hacker Animation
                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                    hack_text = "Initializing Security Scanner..."

                                                                                                                                                                                                                                                                                                    def animate_text(index=0):

                                                                                                                                                                                                                                                                                                        if index <= len(hack_text):

                                                                                                                                                                                                                                                                                                                title.config(text=hack_text[:index])

                                                                                                                                                                                                                                                                                                                        root.after(80, animate_text, index + 1)

                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                        # Main Window
                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                        root = tk.Tk()

                                                                                                                                                                                                                                                                                                                        root.title("WiFi Password Security Auditor")
                                                                                                                                                                                                                                                                                                                        root.geometry("700x550")
                                                                                                                                                                                                                                                                                                                        root.config(bg="black")

                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                        # Title Animation
                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                        title = tk.Label(
                                                                                                                                                                                                                                                                                                                            root,
                                                                                                                                                                                                                                                                                                                                text="",
                                                                                                                                                                                                                                                                                                                                    font=("Courier New", 22, "bold"),
                                                                                                                                                                                                                                                                                                                                        bg="black",
                                                                                                                                                                                                                                                                                                                                            fg="#00ff00"
                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                            title.pack(pady=20)

                                                                                                                                                                                                                                                                                                                                            # -----------------------------
                                                                                                                                                                                                                                                                                                                                            # Main Heading
                                                                                                                                                                                                                                                                                                                                            # -----------------------------
                                                                                                                                                                                                                                                                                                                                            heading = tk.Label(
                                                                                                                                                                                                                                                                                                                                                root,
                                                                                                                                                                                                                                                                                                                                                    text="WiFi Password Security Auditor",
                                                                                                                                                                                                                                                                                                                                                        font=("Courier New", 24, "bold"),
                                                                                                                                                                                                                                                                                                                                                            bg="black",
                                                                                                                                                                                                                                                                                                                                                                fg="cyan"
                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                heading.pack(pady=10)

                                                                                                                                                                                                                                                                                                                                                                # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                # Password Label
                                                                                                                                                                                                                                                                                                                                                                # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                password_label = tk.Label(
                                                                                                                                                                                                                                                                                                                                                                    root,
                                                                                                                                                                                                                                                                                                                                                                        text="ENTER WIFI PASSWORD",
                                                                                                                                                                                                                                                                                                                                                                            font=("Courier New", 14),
                                                                                                                                                                                                                                                                                                                                                                                bg="black",
                                                                                                                                                                                                                                                                                                                                                                                    fg="#00ff00"
                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                    password_label.pack(pady=10)

                                                                                                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                    # Password Entry
                                                                                                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                    password_entry = tk.Entry(
                                                                                                                                                                                                                                                                                                                                                                                        root,
                                                                                                                                                                                                                                                                                                                                                                                            width=30,
                                                                                                                                                                                                                                                                                                                                                                                                font=("Courier New", 18),
                                                                                                                                                                                                                                                                                                                                                                                                    bg="#101010",
                                                                                                                                                                                                                                                                                                                                                                                                        fg="#00ff00",
                                                                                                                                                                                                                                                                                                                                                                                                            insertbackground="#00ff00",
                                                                                                                                                                                                                                                                                                                                                                                                                show="*",
                                                                                                                                                                                                                                                                                                                                                                                                                    bd=3
                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                    password_entry.pack(pady=10)

                                                                                                                                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                    # Show Password Checkbox
                                                                                                                                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                    show_password = tk.Checkbutton(
                                                                                                                                                                                                                                                                                                                                                                                                                        root,
                                                                                                                                                                                                                                                                                                                                                                                                                            text="Show Password",
                                                                                                                                                                                                                                                                                                                                                                                                                                command=toggle_password,
                                                                                                                                                                                                                                                                                                                                                                                                                                    bg="black",
                                                                                                                                                                                                                                                                                                                                                                                                                                        fg="#00ff00",
                                                                                                                                                                                                                                                                                                                                                                                                                                            selectcolor="black",
                                                                                                                                                                                                                                                                                                                                                                                                                                                activebackground="black",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    activeforeground="#00ff00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        font=("Courier New", 11)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                        show_password.pack()

                                                                                                                                                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Check Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                        check_button = tk.Button(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            root,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                text="SCAN PASSWORD",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    font=("Courier New", 14, "bold"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bg="#00ff00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fg="black",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padx=15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pady=5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        command=check_password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        check_button.pack(pady=25)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Result Label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        result_label = tk.Label(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            root,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text="",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    font=("Courier New", 20, "bold"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bg="black"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        result_label.pack(pady=20)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Progress Bar Style
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style = ttk.Style()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style.theme_use("default")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style.configure(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "green.Horizontal.TProgressbar",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                troughcolor="black",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background="#00ff00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bordercolor="black",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lightcolor="#00ff00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                darkcolor="#00ff00"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Progress Bar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                progress = ttk.Progressbar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    root,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        length=400,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mode="determinate",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style="green.Horizontal.TProgressbar"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                progress.pack(pady=15)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Footer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                footer = tk.Label(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    root,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text="Cyber Security Tool | Python Project",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            font=("Courier New", 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bg="black",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fg="gray"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    footer.pack(side="bottom", pady=15)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Start Animation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate_text()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Run App
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # -----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    root.mainloop()